name: Trigger pipeline

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops' 
        type: string
      compute:
        description: 'Azure Machine Learning compute instance name'
        required: true
        default: 'dp100mlopstestcompute' 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run pipeline
      run: |
       az ml job create --file src/job.yml --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
